imports:
  - path: ../../templates/compute/vpc-network.jinja

resources:

- name: base-network
  type: ../../templates/compute/vpc-network.jinja
  properties:
    name: base
    subnets:
  # # Production environment subnets
  #   # Production Google Kubernetes Engine subnet
      - name: gke-pro
        range: 10.30.0.0/18
  # # Staging environments subnets
  #   # Staging Google Kubernetes Engine subnet
      - name: gke-stg
        range: 10.40.0.0/18
  # Development environments subnets
    # Development Google Kubernetes Engine subnet
      - name: gke-dev
        range: 10.50.0.0/16