---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitopsapp-pro-ingress
spec:
  rules:
  - host: production-domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gitopsapp
          servicePort: http