apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsapp
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: TALK
          valueFrom:
            configMapKeyRef:
              name: gitopsapp
              key: talk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitopsapp
data:
  talk: Cloud Native Barcelona