imports:
  - path: ../../templates/container/kubernetes-cluster.jinja
  - path: ../../templates/iam/service-account.jinja

resources:
  - name: kubernetes-cluster
    type: ../../templates/container/kubernetes-cluster.jinja
    properties:
      type: REGIONAL
      network:
        name: base-net
        subnet: gke-pro-sn
        zone: europe-west1
      nodePools:
        - name: compute-pad-n1s1
          machineType: n1-standard-1
          minNodeCount: 2
          preemtible: false

outputs:
  - name: cluster-name
    value: $(ref.kubernetes-cluster.name)
  - name: cluster-location
    value: $(ref.kubernetes-cluster.location)
  - name: cluster-endpoint
    value: $(ref.kubernetes-cluster.endpoint)
  - name: cluster-traefik-lb-address
    value: $(ref.kubernetes-cluster.traefik-lb-address)
  - name: cluster-traefik-lb-dns
    value: $(ref.kubernetes-cluster.traefik-lb-dns)