imports:
  - path: ../../templates/storage/bucket.jinja

resources:

  - name: bucket
    type: ../../templates/storage/bucket.jinja
    properties:
      websiteConfig:
        enabled: true

outputs:

  - name: name
    value: $(ref.bucket.name)
  - name: url
    value: $(ref.bucket.url)