apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./../../../kustomize-bases/gitopsapp

patches:
- ./patches/deployment_replica_count.yaml
- ./patches/cm_talk.yaml

commonLabels:
  version: v1
