imports:
  - path: ../../templates/storage/bucket.jinja

resources:

  - name: bucket
    type: ../../templates/storage/bucket.jinja
    properties:
      name: stg-statics-gitops
      websiteConfig:
        enabled: true

outputs:

  - name: bucket
    value: $(ref.bucket.name)
