apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsapp
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: gitopsapp
              key: db_host
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: gitopsapp
              key: db_user
        - name: DATABASE_PASS
          valueFrom:
            configMapKeyRef:
              name: gitopsapp
              key: db_pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitopsapp
data:
  db_host: host
  db_user: user
  db_pass: pass