imports:
  - path: ../../templates/container/kubernetes-cluster.jinja
  - path: ../../templates/iam/service-account.jinja

resources:
  - name: kubernetes-cluster
    type: ../../templates/container/kubernetes-cluster.jinja
    properties:
      # Type: Can be REGIONAL or LOCAL
      type: ___CLUSTER_TYPE___
      network:
        name: base-net
        #  Subnet: Can be gke-dev-sn, gke-stg-sn or gke-pro-sn
        subnet: ___CLUSTER_SUBNET___
        # For REGIONAL cluster
        region: europe-west1
        # For LOCAL cluster
        zone: europe-west1-b
      nodePools:
        - name: compute-pad-g1s
          machineType: g1-small
          # preemptible: true (default value)
          # autoscaling: true (default value)
          # maxNodeCount: 5 (default value)
          # minNodeCount: 1 (default value)

outputs:
  - name: cluster-name
    value: $(ref.kubernetes-cluster.name)
  - name: cluster-location
    value: $(ref.kubernetes-cluster.location)
  - name: cluster-endpoint
    value: $(ref.kubernetes-cluster.endpoint)
  - name: cluster-traefik-lb-address
    value: $(ref.kubernetes-cluster.traefik-lb-address)
  - name: cluster-traefik-lb-dns
    value: $(ref.kubernetes-cluster.traefik-lb-dns)