---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitopsapp-traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gitops.GKE_TRAEFIK_DNS
    http:
      paths:
      - path: /
        backend:
          serviceName: gitopsapp
          servicePort: http