apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: gitopsapp

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: rvazquez/gitops-demo-front
  newTag: "0.1.0"

configMapGenerator:
- name: gitopsapp